include:
  - project: esperantotech/software/gitlab-ci-common
    ref: 89a8d67023301129fd18dc95af46abfc6871d59c
    file:
      - /rules/generic-workflow-conan.yaml
      - /jobs/generic-k8s-job.yaml
      - /pods/nano-pod.yaml
      - /pods/medium-pod.yaml
      - /rules/exec_maybe_interactively.yaml
      - /jobs/check-top-of-master-template.yaml
      - /jobs/sw-platform-trigger-template.yaml
  - project: esperantotech/software/gitlab-ci-common
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - smoke
  - generate_build
  - build
  - test
  - deploy

default:
  interruptible: true

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/ml-compiler
  PIPELINE_CI_SUBPROJECT: dnnLibrary

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
.release_job:
  rules:
    - &release_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

# Only run job in these cases:
# - if it's a tag pipeline
# - if there is a commit pushed or merged to the default branch (pre-release)
# - if there is a MR open (pre-release, unstable)
.release_or_development_job:
  rules:
    - &release_or_development_job_rule
      if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH) || ($CI_PIPELINE_SOURCE == "merge_request_event")

# Only run job in these cases:
# - if there is a MR open
.development_job:
  rules:
    - &development_job_rule
      if: ($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)

###############################################################################
###############################################################################
###############################################################################

clang-format:
  extends:
    - .template_job
    - .pod_nano
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-22.04-et-sw-platform:0.0.12
  stage: smoke
  rules:
    - *development_job_rule
  variables:
    CMD_SCRIPT: | 
     git fetch origin master
     git clang-format --diff origin/master -- * | grep -e "clang-format did not modify any files$" -e "^no modified files to format$"

check-on-top-of-master:
  extends: .check-on-top-of-master
  stage: .pre
  needs: []
  rules:
    - *development_job_rule

###############################################################################
###############################################################################
###############################################################################

create-sw-platform-branch:
  extends: .create-sw-platform-branch
  stage: generate_build
  needs:
    - check-on-top-of-master
  rules:
    - *development_job_rule

# Generates conan child pipeline
generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu22.04-gcc11
  stage: generate_build
  needs:
    - job: clang-format
      optional: true
    - job: check-on-top-of-master
      optional: true
  rules:
    - *release_or_development_job_rule
  variables:
    TIMEOUT: 15m
    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_build
  artifacts:
    expire_in: 1d 
    paths:
      - conan/build_pipeline.yml

###############################################################################
###############################################################################
###############################################################################

create-sw-platform-trigger:
  extends: .create-sw-platform-trigger
  stage: build
  needs:
    - create-sw-platform-branch
  rules:
    - *development_job_rule

# conan child build pipeline
build:conan:
  stage: build
  needs:
  - generate_build:conan
  rules:
    - *release_or_development_job_rule
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml
tests:integration-repo:
  extends: .meta-trigger
  stage: test
  needs:
    - create-sw-platform-trigger
    - build:conan
  rules:
    - *development_job_rule
  trigger:
    strategy: depend
    include:
      - artifact: generated-trigger-job.yaml
        job: create-sw-platform-trigger

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu22.04-gcc11
  stage: deploy
  needs:
    - build:conan
  rules:
    - *release_job_rule
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m pip install "ecpt>=2.0.0,<3.0.0" --index-url https://sc-artifactory1.esperanto.ai/artifactory/api/pypi/pypi-virtual/simple
      python3 -m ci_promote

###############################################################################
###############################################################################
###############################################################################
