"""
Test the GP-SDK examples.

Tests:
    - test_run_example: Run each of the provided examples
    - test_run_multi_kernel: Run multiple kernels
"""

# pylint: disable=fixme # notes about current GP-SDK issues

from collections import defaultdict
import csv
import logging
import glob
from pathlib import Path
import subprocess
import pytest


KERNEL_LAUNCHERS = {
    "bss": "basic_launcher",
    "busy10sec": "basic_launcher",    
    "c_contructors": "basic_launcher",
    "c_tls": "basic_launcher",
    "check_pmc": "basic_launcher",
    "cpp_contructors": "basic_launcher",
    "cpp_tls": "basic_launcher",
    "data": "basic_launcher",    
    "exception": "basic_launcher",
    "external_tls": "basic_launcher",
    "fftKernel": "fft_launcher",
    "fnodiv": "basic_launcher",
    "gp": "basic_launcher",
    "hang": "basic_launcher",
    "OneTrapOnSync": "basic_launcher",    
    "print": "basic_launcher",
    "print2": "basic_launcher",
    "profiling_simple": "basic_launcher",
    "profiling_stress": "basic_launcher",    
    "saxpy_profiling": "saxpy_launcher",
    "saxpy_scalar": "saxpy_launcher",
    "saxpy_vector": "saxpy_launcher",
    "syncAll": "basic_launcher",
    "syncDeviceBasic": "barrier_launcher",
    "syncAll": "basic_launcher",
    "syncMinion": "barrier_launcher",
    "txfma": "txfma_launcher"
}


KERNELS = list(KERNEL_LAUNCHERS.keys())

SKIP_SYSEMU = ["check_pmc", "busy10sec"]

EXTRA_ARGS = defaultdict(list)
EXTRA_ARGS["saxpy_profiling"] = ["--launch_mult=2"]
EXTRA_ARGS["hang"] = ["--enableCoreDump"]
EXTRA_ARGS["exception"] = ["--enableCoreDump"]
EXTRA_ARGS["bss"] = ["--num_launches=5"]
EXTRA_ARGS["data"] = ["--num_launches=5"]
EXTRA_ARGS["check_pmc"] = ["--kernel_launch_timeout=12"]
EXTRA_ARGS["busy10sec"] = ["--kernel_launch_timeout=12"]
EXTRA_ARGS["OneTrapOnSync"] = ["--enableCoreDump"]

#only needed for device_type = sysemu
EXTRA_ARGS["profiling_stress"] = ["--kernel_launch_timeout=50"]

SHOULD_FAIL = ["hang", "exception"]
JUST_FAIL = ["OneTrapOnSync"]

ERROR_COMMENT = {
    "hang": "Generate code hang",
    "exception": "Generate code exception",
}

MASK_SWEEP_KERNELS = ["syncAll", "syncDeviceBasic", "syncMinion"]
MASK_SWEEP = ["0x1", "0xF", "0xFF", "0xFFFF", "0xFFFFFFFF"]

def check_device_trace(shell, path: Path):
    """Check whether the device trace exists and is well formatted"""
    assert path.exists()
    dt2json = shell.run(f"dt2json -t {path}")
    trace = list(csv.reader(dt2json.stdout.decode("utf-8").splitlines(), delimiter=";"))
    assert trace[0][0] == "TIMESTAMP"
    assert trace[0][1] == "STATS_TYPE"


def check_run_artifacts(shell, device_type: str, nkernels: int = 1):
    """Default checks for run artifacts"""
    if device_type == "sysemu":
        logging.info("Checking UART logs")
        for log in [
            "pu_uart0_tx.log",
            "pu_uart1_tx.log",
            "spio_uart0_tx.log",
            "spio_uart1_tx.log",
        ]:
            assert Path(log).exists()

        uart_log = Path("spio_uart0_tx.log").read_text(encoding="utf-8")
        assert "Initialize Minion Shire" in uart_log

        logging.info("Checking sysemu logs")
        sysemu_log_path = Path("sysemu.log0")
        assert sysemu_log_path.exists()
        sysemu_log = sysemu_log_path.read_text(encoding="utf-8")
        assert "ERROR" not in sysemu_log
        assert "FATAL" not in sysemu_log

    logging.info("Checking device trace")
    if nkernels == 1:
        check_device_trace(
            shell,
            Path("traceKernels_dev0_0.bin"),
        )
    else:
        for i in range(nkernels):
            check_device_trace(
                shell,
                Path(f"traceKernels_dev0_0_{i}.bin"),
            )


def check_core_dump(gdb, elf: Path, comment: str, skip_gdb: bool):
    """Check whether the core dump exists and is debuggable"""
    logging.info("Checking core dump")
    core_dumps = glob.glob("core.*.etsoc.*")
    assert len(core_dumps) == 1, "Should create exactly one core dump file"
    if skip_gdb:
        logging.info("Skipping gdb checks")
        return
    gdb = gdb(f"{elf} {core_dumps[0]}")
    gdb.eval("c", [])
    gdb.read_until("Core was generated by")
    gdb.eval("set pagination off", [])
    gdb.eval("set width unlimited", [])
    gdb.eval("set disassemble-next-line on", [])
    gdb.eval(
        "info threads",
        [
            "*entryPoint_0*args*",
            "*at*.cc:*",
            "*",
            "*Current thread is 1*",
            "*Id*Target*Id*Frame*",
        ],
    )
    gdb.read_until("1023")
    gdb.eval("list")
    gdb.read_until(comment)
    gdb.close()


@pytest.mark.parametrize("device_type", ["sysemu", "silicon"])
@pytest.mark.parametrize("kernel", KERNEL_LAUNCHERS.keys())
def test_run_example(shell, device_type, kernel, build_dir, gdb, request):
    """Run one of the provided examples"""
    if not build_dir.exists():
        pytest.skip("the examples have not been built")
    if device_type == "sysemu" and kernel in SKIP_SYSEMU:
        pytest.skip(f"do not run {kernel} on {device_type}")
    logging.info("Running %s on %s", kernel, device_type)
    kernel_path = build_dir.device / "tests" / f"{kernel}.elf"
    launch_cmd = " ".join(
        [
            str(build_dir.host / "sdk" / KERNEL_LAUNCHERS[kernel]),
            f"--kernel_path={kernel_path}",
            f"--device_type={device_type}",
        ]
        + EXTRA_ARGS[kernel]
    )
    if kernel in SHOULD_FAIL:
        with pytest.raises(subprocess.CalledProcessError):
            shell.run(launch_cmd)
        check_core_dump(
            gdb,
            kernel_path.parent / (kernel_path.name + "_dbg"),
            ERROR_COMMENT[kernel],
            skip_gdb = request.config.getoption("--skip-gdb"),
        )
    elif kernel in JUST_FAIL:
        with pytest.raises(subprocess.CalledProcessError):
            shell.run(launch_cmd)
    elif kernel in MASK_SWEEP_KERNELS:
        for mask in MASK_SWEEP:
            mask_cmd = launch_cmd + " --shire_mask=" + mask
            shell.run(mask_cmd)
    else:
        shell.run(launch_cmd)

    if kernel not in JUST_FAIL:    
        check_run_artifacts(shell, device_type)


@pytest.mark.parametrize("device_type", ["sysemu", "silicon"])
def test_run_multi_kernel(shell, device_type, build_dir):
    """Run multi kernel example"""
    if not build_dir.exists():
        pytest.skip("the examples have not been built")
    kernels = ["bss", "saxpy_scalar"]
    logging.info("Running %s on %s", kernels, device_type)
    kernel_paths = [build_dir.device / "tests" / f"{kernel}.elf" for kernel in kernels]
    launch_cmd = " ".join(
        [
            str(build_dir.host / "sdk/multiKernel_launcher"),
            f"--kernel_path1={kernel_paths[0]}",
            f"--kernel_path2={kernel_paths[1]}",
            f"--device_type={device_type}",
        ]
    )
    shell.run(f"( cd {shell.tmp_path} ; {launch_cmd} )")
    check_run_artifacts(shell, device_type, nkernels=2)
