/*-------------------------------------------------------------------------
 * Copyright (C) 2021, Esperanto Technologies Inc.
 * The copyright to the computer program(s) herein is the
 * property of Esperanto Technologies, Inc. All Rights Reserved.
 * The program(s) may be used and/or copied only with
 * the written permission of Esperanto Technologies and
 * in accordance with the terms and conditions stipulated in the
 * agreement/contract under which the program(s) have been supplied.
 *-------------------------------------------------------------------------
 */

#include "LibApiImplSel.h"
#include "dnnLibraryApi/LibApi.h"

#include <cctype>
#include <cmath>

namespace dnn_lib {

////////////////////////////////////////////////////////////////////////////////
// INSTRUCTION TABLE (autogenerated from excels ?)
////////////////////////////////////////////////////////////////////////////////
static constexpr auto instrConfigTable = std::experimental::make_array(
  // clang-format off
    // INSTR_CONFIG_TABLE_BEGIN
    // ET_adaptiveavgpool
    instrConfig {
      "AdaptiveAvgPool", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_allocactivation
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_argmax
    instrConfig {
      "ArgMax", // name
      1, // # outs
      1,  // # ins
      {mbAxis, mbKeepDims}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_avgpool
    instrConfig {
      "AvgPool", // name
      1, // # outs
      1,  // # ins
      {mbKernels, mbStrides, mbPads, mbLayout, mbCountIncludePads}, // members
      1, // template param mask
      {"Threaded"}, // impl versions
      implSel::AvgPool, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_batchedadd
    instrConfig {
      "BatchedAdd", // name
      1, // # outs
      2,  // # ins
      {}, // members
      7, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchedreduceadd
    instrConfig {
      "BatchedReduceAdd", // name
      1, // # outs
      1,  // # ins
      {mbAxis}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchedreducemin
    instrConfig {
      "BatchedReduceMin", // name
      1, // # outs
      1,  // # ins
      {mbAxes}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchonehot
    instrConfig {
      "BatchOneHot", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convertto
    instrConfig {
      "ConvertTo", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {"Vectorized"}, // impl versions
      implSel::defaultSel<2>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_int8converter
    instrConfig {
      "Int8Converter", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_channelwisequantizedconvolution
    instrConfig {
      "ChannelWiseQuantizedConvolution", // name
      1, // # outs
      7,  // # ins
      {mbKernels, mbStrides, mbPads, mbGroup, mbDilation, mbFusedActivation, mbFusedActivationArgs}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_channelwisequantizedconvolution3d
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_convolution
    instrConfig {
      "Convolution", // name
      1, // # outs
      3,  // # ins
      {mbKernels, mbStrides, mbPads, mbGroup, mbDilation, mbFusedActivation, mbFusedActivationArgs}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convolution3d
    instrConfig {
      "Convolution3D", // name
      1, // # outs
      3,  // # ins
      {mbKernels, mbStrides, mbPads, mbGroup}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convtranspose
    instrConfig {
      "ConvTranspose", // name
      1, // # outs
      3,  // # ins
      {mbKernels, mbStrides, mbPads, mbGroup, mbDilation}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_copy
    instrConfig {
      "Copy", // name
      1, // # outs
      1,  // # ins
      {}, // members
      1, // template param mask
      {"Tensorized"}, // impl versions
      implSel::Copy, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::untouched, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::untouched, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::dirty, operandState::untouched}}},
      {0x1, 0x0} // evict available mask
    },
    // ET_crossentropyloss
    instrConfig {
      "CrossEntropyLoss", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_cumsum
    instrConfig {
      "CumSum", // name
      1, // # outs
      1,  // # ins
      {mbExclusive, mbReverse}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_deallocactivation
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_debugprint
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_dequantize
    instrConfig {
      "Dequantize", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementadd
    instrConfig {
      "ElementAdd", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementand
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_elementcmpeq
    instrConfig {
      "ElementCmpEQ", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpEQ, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementcmplte
    instrConfig {
      "ElementCmpLTE", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpLTE, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementcmplt
    instrConfig {
      "ElementCmpLT", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpLT, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementdiv
    instrConfig {
      "ElementDiv", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementexp
    instrConfig {
      "ElementExp", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementisnan
    instrConfig {
      "ElementIsNaN", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementlog
    instrConfig {
      "ElementLog", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmax
    instrConfig {
      "ElementMax", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmin
    instrConfig {
      "ElementMin", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmul
    instrConfig {
      "ElementMul", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementor
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_elementpow
    instrConfig {
      "ElementPow", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementselect
    instrConfig {
      "ElementSelect", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementsub
    instrConfig {
      "ElementSub", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementxor
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_embeddingbag
    instrConfig {
      "EmbeddingBag", // name
      1, // # outs
      4,  // # ins
      {mbHasEndOffset}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_embeddingbagbyterowwiseoffsets
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_emptyoperator
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_maxsplat
    instrConfig {
      "MaxSplat", // name
      1, // # outs
      1,  // # ins
      {mbValue}, // members
      2, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::MaxSplat, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_extracttensor
    instrConfig {
      "ExtractTensor", // name
      1, // # outs
      1,  // # ins
      {mbOffsets}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_flip
    instrConfig {
      "Flip", // name
      1, // # outs
      1,  // # ins
      {mbAxis}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_flushL3
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_fullyconnected
    instrConfig {
      "FullyConnected", // name
      1, // # outs
      3,  // # ins
      {}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_fusedrowwisequantizedsparselengthsweightedsum
    instrConfig {
      "FusedRowwiseQuantizedSparseLengthsWeightedSum", // name
      1, // # outs
      4,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_fusedrowwisequantizedsparselengthssum
    instrConfig {
      "FusedRowwiseQuantizedSparseLengthsSum", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_gather
    instrConfig {
      "Gather", // name
      1, // # outs
      2,  // # ins
      {mbBatchDims}, // members
      6, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x1} // evict available mask
    },
    // ET_gatherranges
    instrConfig {
      "GatherRanges", // name
      2, // # outs
      2,  // # ins
      {}, // members
      12, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_inserttensor
    instrConfig {
      "InsertTensor", // name
      1, // # outs
      1,  // # ins
      {mbOffsets, mbCount, mbAxis}, // members
      2, // template param mask
      {"Threaded"}, // impl versions
      implSel::InsertTensor, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x1, 0x1} // evict available mask
    },
    // ET_intlookuptable
    instrConfig {
      "IntLookupTable", // name
      1, // # outs
      2,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthsrangefill
    instrConfig {
      "LengthsRangeFill", // name
      1, // # outs
      1,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthssum
    instrConfig {
      "LengthsSum", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthstoranges
    instrConfig {
      "LengthsToRanges", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_localresponsenormalization
    instrConfig {
      "LocalResponseNormalization", // name
      2, // # outs
      1,  // # ins
      {mbHalfWindowSize, mbAlpha, mbBeta, mbK}, // members
      2, // template param mask
      {"Vectorized"}, // impl versions
      implSel::LocalResponseNormalization, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_matmul
    instrConfig {
      "MatMul", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_maxpool
    instrConfig {
      "MaxPool", // name
      1, // # outs
      1,  // # ins
      {mbKernels, mbStrides, mbPads, mbLayout}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_maxpoolwithargmax
    instrConfig {
      "MaxPoolWithArgMax", // name
      2, // # outs
      1,  // # ins
      {mbKernels, mbStrides, mbPads, mbLayout}, // members
      5, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_modulo
    instrConfig {
      "Modulo", // name
      1, // # outs
      1,  // # ins
      {mbDivisor, mbSignFollowDivisor}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_nonmaxsuppression
    instrConfig {
      "NonMaxSuppression", // name
      2, // # outs
      2,  // # ins
      {mbCenterPointBox, mbMaxOutputBoxesPerClass, mbIouThreshold, mbScoreThreshold, mbIsTFVersion4}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_quantizationprofile
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_quantize
    instrConfig {
      "Quantize", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_rescalequantized
    instrConfig {
      "RescaleQuantized", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_resizebilinear
    instrConfig {
      "ResizeBilinear", // name
      1, // # outs
      1,  // # ins
      {mbRszScale}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_resizenearest
    instrConfig {
      "ResizeNearest", // name
      1, // # outs
      1,  // # ins
      {mbRszScale}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_rowwisequantizedfullyconnected
    instrConfig {
      "RowwiseQuantizedFullyConnected", // name
      1, // # outs
      5,  // # ins
      {}, // members
      0, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::RowwiseQuantizedFullyConnected, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_rowwisequantizedsparselengthsweightedsum
    instrConfig {
      "RowwiseQuantizedSparseLengthsWeightedSum", // name
      1, // # outs
      6,  // # ins
      {}, // members
      33, // template param mask
      {"Vectorized"}, // impl versions
      implSel::RowwiseQuantizedSparseLengthsWeightedSum, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_scatterdata
    instrConfig {
      "ScatterData", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sigmoid
    instrConfig {
      "Sigmoid", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_softmax
    instrConfig {
      "SoftMax", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {"Vectorized"}, // impl versions
      implSel::SoftMax, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_spacetodepth
    instrConfig {
      "SpaceToDepth", // name
      1, // # outs
      1,  // # ins
      {mbBlockSize}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparselengthssum
    instrConfig {
      "SparseLengthsSum", // name
      1, // # outs
      3,  // # ins
      {}, // members
      5, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparselengthsweightedsum
    instrConfig {
      "SparseLengthsWeightedSum", // name
      1, // # outs
      4,  // # ins
      {}, // members
      10, // template param mask
      {"Threaded"}, // impl versions
      implSel::SparseLengthsWeightedSum, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_sparsetodense
    instrConfig {
      "SparseToDense", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparsetodensemask
    instrConfig {
      "SparseToDenseMask", // name
      1, // # outs
      4,  // # ins
      {mbMask}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_splat
    instrConfig {
      "Splat", // name
      1, // # outs
      0,  // # ins
      {mbValue}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty}}},
      // L2 states per impl
      {{{operandState::dirty}}},
      // CB states per impl
      {{{operandState::untouched}}},
      {0x1} // evict available mask
    },
    // ET_sync
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_syncopy
    instrConfig {
      "Syncopy", // name
      1, // # outs
      1,  // # ins
      {mbSyncOffset}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_tanh
    instrConfig {
      "Tanh", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_tensorview
    instrConfig {
      "TensorView", // name
      1, // # outs
      1,  // # ins
      {mbOffsets}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_topk
    instrConfig {
      "TopK", // name
      2, // # outs
      1,  // # ins
      {mbTopK}, // members
      4, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_touch
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_traceevent
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_transpose
    instrConfig {
      "Transpose", // name
      1, // # outs
      1,  // # ins
      {mbShuffle}, // members
      2, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::Transpose, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_inhosttransform
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_outhosttransform
    instrConfig {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    }
    // INSTR_CONFIG_TABLE_END
    // clang-format on
);

operandState instrConfig::getOperandStateL1(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateL1[implIdx][operand];
}
operandState instrConfig::getOperandStateL2(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateL2[implIdx][operand];
}
operandState instrConfig::getOperandStateCB(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateCB[implIdx][operand];
}
bool instrConfig::getOperandAutoEvict(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return ((evictAvailableMask[implIdx] >> operand) & 1);
}
operandState instrConfig::getSrcStateL1(size_t implIdx, size_t idx) {
  return getOperandStateL1(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getSrcStateL2(size_t implIdx, size_t idx) {
  return getOperandStateL2(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getSrcStateCB(size_t implIdx, size_t idx) {
  return getOperandStateCB(implIdx, idx + nrOutputTensors);
}
bool instrConfig::getSrcAutoEvict(size_t implIdx, size_t idx) {
  return getOperandAutoEvict(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getDstStateL1(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateL1(implIdx, idx);
}
operandState instrConfig::getDstStateL2(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateL2(implIdx, idx);
}
operandState instrConfig::getDstStateCB(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateCB(implIdx, idx);
}
bool instrConfig::getDstAutoEvict(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandAutoEvict(implIdx, idx);
}

//////////////

bool caseInsCharCompare(char a, char b) {
  return (std::toupper(a) == std::toupper(b));
}

bool caseInsCompare(const std::string& s1, const std::string& s2) {
  return ((s1.size() == s2.size()) && equal(s1.begin(), s1.end(), s2.begin(), caseInsCharCompare));
}

bool getInstrConfig(const std::string& operatorName, instrConfig& instConfig) {
  for (auto it = instrConfigTable.begin(); it != instrConfigTable.end(); ++it) {
    if (caseInsCompare(it->name, operatorName)) {
      instConfig = *it;
      return true;
    }
  }
  return false;
}

size_t getInstrNumCycles(const std::string& operatorName, size_t assignedMinions,
                         const std::vector<LibTensor*>& operands) {
  size_t result = 2000;
  if (caseInsCompare("FusedRowwiseQuantizedSparseLengthsWeightedSum", operatorName)) {
    // Computes lines to read from DDR
    size_t lineSize = operands[0]->strides()[0];
    size_t lineCL = (size_t)ceilf((float)lineSize / 64.0f); // Converts to cachelines
    size_t lookups = operands[1]->dims()[0];
    // Data read from the embedding
    size_t totalBytes = lineCL * lookups * 64;
    // Data read to get lookup indices and the weight
    // TODO: need to get the lookup index size and weight size
    totalBytes += lookups * 8 + lookups * 4;

    // Cycles is amount of CL to read by cycles per CL
    // TODO: gather this info from device
    float ddrBytesPerCycle = 133.0f * 0.55f;
    float ddrBytesPerMinion = ddrBytesPerCycle / 1024.0f;
    float minions = (float)assignedMinions;
    float ddrCycles = (float)totalBytes / ddrBytesPerMinion / minions;

    // Total amount of time is fixed time plus ddr time
    result = 4000 + (size_t)ddrCycles;
  } else if (caseInsCompare("FusedRowwiseQuantizedSparseLengthsSum", operatorName)) {
    // Computes lines to read from DDR
    size_t lineSize = operands[0]->strides()[0];
    size_t lineCL = (size_t)ceilf((float)lineSize / 64.0f); // Converts to cachelines
    size_t lookups = operands[1]->dims()[0];
    // Data read from the embedding
    size_t totalBytes = lineCL * lookups * 64;
    // Data read to get lookup indices and the weight
    // TODO: need to get the lookup index size
    totalBytes += lookups * 8;

    // Cycles is amount of CL to read by cycles per CL
    // TODO: gather this info from device
    float ddrBytesPerCycle = 133.0f * 0.55f;
    float ddrBytesPerMinion = ddrBytesPerCycle / 1024.0f;
    float minions = (float)assignedMinions;
    float ddrCycles = (float)totalBytes / ddrBytesPerMinion / minions;

    // Total amount of time is fixed time plus ddr time
    result = 4000 + (size_t)ddrCycles;
  }

  return result;
}

} // end namespace dnn_lib
