/*-------------------------------------------------------------------------
 * Copyright (C) 2021, Esperanto Technologies Inc.
 * The copyright to the computer program(s) herein is the
 * property of Esperanto Technologies, Inc. All Rights Reserved.
 * The program(s) may be used and/or copied only with
 * the written permission of Esperanto Technologies and
 * in accordance with the terms and conditions stipulated in the
 * agreement/contract under which the program(s) have been supplied.
 *-------------------------------------------------------------------------
 */

// Local
#include "LibApiImplSel.h"
#include "LibTensor.h"
#include "dnnLibraryApi/LibApi.h"

// STD
#include <cctype>
#include <cmath>
#include <cstring>
#include <experimental/array> // not available on macos - if we ever need dnnLibraryApi available there we should remove the std::experimental::make_array
#include <memory>

namespace dnn_lib {

// Instruction properties struct internal
struct instrConfigInt {
  using operandStateArray = std::array<operandState, maxNrOperands>;
  using implStateArray = std::array<operandStateArray, maxImplVersions + 1>;
  using sel_fnc_t = size_t (*)(std::vector<LibTensor*>&, std::vector<LibTensor*>&);

  char name[maxInstrConfigStrLen];
  size_t nrOutputTensors; // number of output and in/out tensor operands
  size_t nrInputTensors;  // number of input tensor operands
  std::array<instrMembers, (long unsigned int)instrMembers::mbMaxMembers> members;
  uint64_t templateMask;
  std::array<char[maxInstrConfigStrLen], maxImplVersions> versions;
  sel_fnc_t implSel;

  implStateArray stateL1;
  implStateArray stateL2;
  implStateArray stateCB;
  std::array<uint64_t, maxImplVersions + 1> evictAvailableMask;
};

////////////////////////////////////////////////////////////////////////////////
// INSTRUCTION TABLE (autogenerated from excels ?)
////////////////////////////////////////////////////////////////////////////////
static constexpr auto instrConfigTable = std::experimental::make_array(
  // clang-format off
    // INSTR_CONFIG_TABLE_BEGIN
    // ET_adaptiveavgpool
    instrConfigInt {
      "AdaptiveAvgPool", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_allocactivation
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_argmax
    instrConfigInt {
      "ArgMax", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbAxis, instrMembers::mbKeepDims}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_avgpool
    instrConfigInt {
      "AvgPool", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbLayout, instrMembers::mbCountIncludePads}, // members
      1, // template param mask
      {"Threaded"}, // impl versions
      implSel::AvgPool, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_batchedadd
    instrConfigInt {
      "BatchedAdd", // name
      1, // # outs
      2,  // # ins
      {}, // members
      7, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchedreduceadd
    instrConfigInt {
      "BatchedReduceAdd", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbAxis}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchedreducemin
    instrConfigInt {
      "BatchedReduceMin", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbAxes}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_batchonehot
    instrConfigInt {
      "BatchOneHot", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convertto
    instrConfigInt {
      "ConvertTo", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {"Vectorized"}, // impl versions
      implSel::defaultSel<2>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_int8converter
    instrConfigInt {
      "Int8Converter", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_channelwisequantizedconvolution
    instrConfigInt {
      "ChannelWiseQuantizedConvolution", // name
      1, // # outs
      7,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbGroup, instrMembers::mbDilation, instrMembers::mbFusedActivation, instrMembers::mbFusedActivationArgs}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_channelwisequantizedconvolution3d
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_convolution
    instrConfigInt {
      "Convolution", // name
      1, // # outs
      3,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbGroup, instrMembers::mbDilation, instrMembers::mbFusedActivation, instrMembers::mbFusedActivationArgs}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convolution3d
    instrConfigInt {
      "Convolution3D", // name
      1, // # outs
      3,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbGroup}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_convtranspose
    instrConfigInt {
      "ConvTranspose", // name
      1, // # outs
      3,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbGroup, instrMembers::mbDilation}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_copy
    instrConfigInt {
      "Copy", // name
      1, // # outs
      1,  // # ins
      {}, // members
      1, // template param mask
      {"Tensorized"}, // impl versions
      implSel::Copy, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::untouched, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::untouched, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::dirty, operandState::untouched}}},
      {0x1, 0x0} // evict available mask
    },
    // ET_crossentropyloss
    instrConfigInt {
      "CrossEntropyLoss", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_cumsum
    instrConfigInt {
      "CumSum", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbExclusive, instrMembers::mbReverse}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_deallocactivation
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_debugprint
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_dequantize
    instrConfigInt {
      "Dequantize", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementadd
    instrConfigInt {
      "ElementAdd", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementand
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_elementcmpeq
    instrConfigInt {
      "ElementCmpEQ", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpEQ, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementcmplte
    instrConfigInt {
      "ElementCmpLTE", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpLTE, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementcmplt
    instrConfigInt {
      "ElementCmpLT", // name
      1, // # outs
      2,  // # ins
      {}, // members
      6, // template param mask
      {"Vectorized"}, // impl versions
      implSel::ElementCmpLT, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_elementdiv
    instrConfigInt {
      "ElementDiv", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementexp
    instrConfigInt {
      "ElementExp", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementisnan
    instrConfigInt {
      "ElementIsNaN", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementlog
    instrConfigInt {
      "ElementLog", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmax
    instrConfigInt {
      "ElementMax", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmin
    instrConfigInt {
      "ElementMin", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementmul
    instrConfigInt {
      "ElementMul", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementor
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_elementpow
    instrConfigInt {
      "ElementPow", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementselect
    instrConfigInt {
      "ElementSelect", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementsub
    instrConfigInt {
      "ElementSub", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_elementxor
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_embeddingbag
    instrConfigInt {
      "EmbeddingBag", // name
      1, // # outs
      4,  // # ins
      {instrMembers::mbHasEndOffset}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_embeddingbagbyterowwiseoffsets
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_emptyoperator
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_maxsplat
    instrConfigInt {
      "MaxSplat", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbValue}, // members
      2, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::MaxSplat, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_extracttensor
    instrConfigInt {
      "ExtractTensor", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbOffsets}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_flip
    instrConfigInt {
      "Flip", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbAxis}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_flushL3
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_fullyconnected
    instrConfigInt {
      "FullyConnected", // name
      1, // # outs
      3,  // # ins
      {}, // members
      9, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_fusedrowwisequantizedsparselengthsweightedsum
    instrConfigInt {
      "FusedRowwiseQuantizedSparseLengthsWeightedSum", // name
      1, // # outs
      4,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_fusedrowwisequantizedsparselengthssum
    instrConfigInt {
      "FusedRowwiseQuantizedSparseLengthsSum", // name
      1, // # outs
      3,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_gather
    instrConfigInt {
      "Gather", // name
      1, // # outs
      2,  // # ins
      {instrMembers::mbBatchDims}, // members
      6, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x1} // evict available mask
    },
    // ET_gatherranges
    instrConfigInt {
      "GatherRanges", // name
      2, // # outs
      2,  // # ins
      {}, // members
      12, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_inserttensor
    instrConfigInt {
      "InsertTensor", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbOffsets, instrMembers::mbCount, instrMembers::mbAxis}, // members
      2, // template param mask
      {"Threaded"}, // impl versions
      implSel::InsertTensor, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x1, 0x1} // evict available mask
    },
    // ET_intlookuptable
    instrConfigInt {
      "IntLookupTable", // name
      1, // # outs
      2,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthsrangefill
    instrConfigInt {
      "LengthsRangeFill", // name
      1, // # outs
      1,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthssum
    instrConfigInt {
      "LengthsSum", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_lengthstoranges
    instrConfigInt {
      "LengthsToRanges", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_localresponsenormalization
    instrConfigInt {
      "LocalResponseNormalization", // name
      2, // # outs
      1,  // # ins
      {instrMembers::mbHalfWindowSize, instrMembers::mbAlpha, instrMembers::mbBeta, instrMembers::mbK}, // members
      2, // template param mask
      {"Vectorized"}, // impl versions
      implSel::LocalResponseNormalization, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_matmul
    instrConfigInt {
      "MatMul", // name
      1, // # outs
      2,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_maxpool
    instrConfigInt {
      "MaxPool", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbLayout}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_maxpoolwithargmax
    instrConfigInt {
      "MaxPoolWithArgMax", // name
      2, // # outs
      1,  // # ins
      {instrMembers::mbKernels, instrMembers::mbStrides, instrMembers::mbPads, instrMembers::mbLayout}, // members
      5, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_modulo
    instrConfigInt {
      "Modulo", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbDivisor, instrMembers::mbSignFollowDivisor}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_nonmaxsuppression
    instrConfigInt {
      "NonMaxSuppression", // name
      2, // # outs
      2,  // # ins
      {instrMembers::mbCenterPointBox, instrMembers::mbMaxOutputBoxesPerClass, instrMembers::mbIouThreshold, instrMembers::mbScoreThreshold, instrMembers::mbIsTFVersion4}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_quantizationprofile
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_quantize
    instrConfigInt {
      "Quantize", // name
      1, // # outs
      1,  // # ins
      {}, // members
      3, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_rescalequantized
    instrConfigInt {
      "RescaleQuantized", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_resizebilinear
    instrConfigInt {
      "ResizeBilinear", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbRszScale}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_resizenearest
    instrConfigInt {
      "ResizeNearest", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbRszScale}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_rowwisequantizedfullyconnected
    instrConfigInt {
      "RowwiseQuantizedFullyConnected", // name
      1, // # outs
      5,  // # ins
      {}, // members
      0, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::RowwiseQuantizedFullyConnected, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_rowwisequantizedsparselengthsweightedsum
    instrConfigInt {
      "RowwiseQuantizedSparseLengthsWeightedSum", // name
      1, // # outs
      6,  // # ins
      {}, // members
      33, // template param mask
      {"Vectorized"}, // impl versions
      implSel::RowwiseQuantizedSparseLengthsWeightedSum, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_scatterdata
    instrConfigInt {
      "ScatterData", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sigmoid
    instrConfigInt {
      "Sigmoid", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_softmax
    instrConfigInt {
      "SoftMax", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {"Vectorized"}, // impl versions
      implSel::SoftMax, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_spacetodepth
    instrConfigInt {
      "SpaceToDepth", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbBlockSize}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparselengthssum
    instrConfigInt {
      "SparseLengthsSum", // name
      1, // # outs
      3,  // # ins
      {}, // members
      5, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparselengthsweightedsum
    instrConfigInt {
      "SparseLengthsWeightedSum", // name
      1, // # outs
      4,  // # ins
      {}, // members
      10, // template param mask
      {"Threaded"}, // impl versions
      implSel::SparseLengthsWeightedSum, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean},
        {operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_sparsetodense
    instrConfigInt {
      "SparseToDense", // name
      1, // # outs
      2,  // # ins
      {}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_sparsetodensemask
    instrConfigInt {
      "SparseToDenseMask", // name
      1, // # outs
      4,  // # ins
      {instrMembers::mbMask}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean, operandState::clean, operandState::clean, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_splat
    instrConfigInt {
      "Splat", // name
      1, // # outs
      0,  // # ins
      {instrMembers::mbValue}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty}}},
      // L2 states per impl
      {{{operandState::dirty}}},
      // CB states per impl
      {{{operandState::untouched}}},
      {0x1} // evict available mask
    },
    // ET_sync
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_syncopy
    instrConfigInt {
      "Syncopy", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbSyncOffset}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_tanh
    instrConfigInt {
      "Tanh", // name
      1, // # outs
      1,  // # ins
      {}, // members
      2, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_tensorview
    instrConfigInt {
      "TensorView", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbOffsets}, // members
      1, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_topk
    instrConfigInt {
      "TopK", // name
      2, // # outs
      1,  // # ins
      {instrMembers::mbTopK}, // members
      4, // template param mask
      {}, // impl versions
      implSel::defaultSel<1>, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched, operandState::untouched}}},
      {0x0} // evict available mask
    },
    // ET_touch
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_traceevent
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_transpose
    instrConfigInt {
      "Transpose", // name
      1, // # outs
      1,  // # ins
      {instrMembers::mbShuffle}, // members
      2, // template param mask
      {"Aligned32Bytes"}, // impl versions
      implSel::Transpose, // custom impl selector
      // L1 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // L2 states per impl
      {{{operandState::dirty, operandState::clean},
        {operandState::dirty, operandState::clean}}},
      // CB states per impl
      {{{operandState::untouched, operandState::untouched},
        {operandState::untouched, operandState::untouched}}},
      {0x0, 0x0} // evict available mask
    },
    // ET_inhosttransform
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    },
    // ET_outhosttransform
    instrConfigInt {
      "notImplemented", // name
      0, // # outs
      0,  // # ins
      {}, // members
      0, // template param mask
      {}, // impl versions
      nullptr, // custom impl selector
      // L1 states per impl
      {{operandState::untouched}},
      // L2 states per impl
      {{operandState::untouched}},
      // CB states per impl
      {{operandState::untouched}},
      {0} // evict available mask
    }
    // INSTR_CONFIG_TABLE_END
    // clang-format on
);

operandState instrConfig::getOperandStateL1(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateL1[implIdx][operand];
}
operandState instrConfig::getOperandStateL2(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateL2[implIdx][operand];
}
operandState instrConfig::getOperandStateCB(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return stateCB[implIdx][operand];
}
bool instrConfig::getOperandAutoEvict(size_t implIdx, size_t operand) {
  assert(operand < nrOutputTensors + nrInputTensors);
  return ((evictAvailableMask[implIdx] >> operand) & 1);
}
operandState instrConfig::getSrcStateL1(size_t implIdx, size_t idx) {
  return getOperandStateL1(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getSrcStateL2(size_t implIdx, size_t idx) {
  return getOperandStateL2(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getSrcStateCB(size_t implIdx, size_t idx) {
  return getOperandStateCB(implIdx, idx + nrOutputTensors);
}
bool instrConfig::getSrcAutoEvict(size_t implIdx, size_t idx) {
  return getOperandAutoEvict(implIdx, idx + nrOutputTensors);
}
operandState instrConfig::getDstStateL1(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateL1(implIdx, idx);
}
operandState instrConfig::getDstStateL2(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateL2(implIdx, idx);
}
operandState instrConfig::getDstStateCB(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandStateCB(implIdx, idx);
}
bool instrConfig::getDstAutoEvict(size_t implIdx, size_t idx) {
  assert(idx < nrOutputTensors);
  return getOperandAutoEvict(implIdx, idx);
}

//////////////

bool caseInsCharCompare(char a, char b) {
  return (std::toupper(a) == std::toupper(b));
}

bool caseInsCompare(const std::string& s1, const std::string& s2) {
  return ((s1.size() == s2.size()) && equal(s1.begin(), s1.end(), s2.begin(), caseInsCharCompare));
}

bool getInstrConfig(const std::string& operatorName, instrConfigInt& instConfig) {
  for (auto it = instrConfigTable.begin(); it != instrConfigTable.end(); ++it) {
    if (caseInsCompare(it->name, operatorName)) {
      instConfig = *it;
      return true;
    }
  }
  return false;
}

bool getInstrConfig(const std::string& operatorName, instrConfig& instConfig) {
  instrConfigInt instConfigInt;

  // Looks for the internal config
  if (!getInstrConfig(operatorName, instConfigInt)) {
    return false;
  }

  // Converts to the API config
  std::memcpy(instConfig.name, instConfigInt.name, maxInstrConfigStrLen);
  instConfig.nrOutputTensors = instConfigInt.nrOutputTensors;
  instConfig.nrInputTensors = instConfigInt.nrInputTensors;
  instConfig.members = instConfigInt.members;
  instConfig.templateMask = instConfigInt.templateMask;
  for (size_t i = 0; i < maxImplVersions; i++) {
    std::memcpy(instConfig.versions[i], instConfigInt.versions[i], maxInstrConfigStrLen);
  }
  instConfig.implSel = instConfigInt.implSel;
  instConfig.stateL1 = instConfigInt.stateL1;
  instConfig.stateL2 = instConfigInt.stateL2;
  instConfig.stateCB = instConfigInt.stateCB;
  instConfig.evictAvailableMask = instConfigInt.evictAvailableMask;

  return true;
}

size_t getInstrNumCycles(const std::string& operatorName, size_t assignedMinions, const std::vector<Tensor>& operands) {
  size_t result = 2000;
  if (caseInsCompare("FusedRowwiseQuantizedSparseLengthsWeightedSum", operatorName)) {
    // Computes lines to read from DDR
    size_t lineSize = operands[0].strides[0];
    size_t lineCL = (size_t)ceilf((float)lineSize / 64.0f); // Converts to cachelines
    size_t lookups = operands[1].sizes[0];
    // Data read from the embedding
    size_t totalBytes = lineCL * lookups * 64;
    // Data read to get lookup indices and the weight
    // TODO: need to get the lookup index size and weight size
    totalBytes += lookups * 8 + lookups * 4;

    // Cycles is amount of CL to read by cycles per CL
    // TODO: gather this info from device
    float ddrBytesPerCycle = 133.0f * 0.55f;
    float ddrBytesPerMinion = ddrBytesPerCycle / 1024.0f;
    float minions = (float)assignedMinions;
    float ddrCycles = (float)totalBytes / ddrBytesPerMinion / minions;

    // Total amount of time is fixed time plus ddr time
    result = 4000 + (size_t)ddrCycles;
  } else if (caseInsCompare("FusedRowwiseQuantizedSparseLengthsSum", operatorName)) {
    // Computes lines to read from DDR
    size_t lineSize = operands[0].strides[0];
    size_t lineCL = (size_t)ceilf((float)lineSize / 64.0f); // Converts to cachelines
    size_t lookups = operands[1].sizes[0];
    // Data read from the embedding
    size_t totalBytes = lineCL * lookups * 64;
    // Data read to get lookup indices and the weight
    // TODO: need to get the lookup index size
    totalBytes += lookups * 8;

    // Cycles is amount of CL to read by cycles per CL
    // TODO: gather this info from device
    float ddrBytesPerCycle = 133.0f * 0.55f;
    float ddrBytesPerMinion = ddrBytesPerCycle / 1024.0f;
    float minions = (float)assignedMinions;
    float ddrCycles = (float)totalBytes / ddrBytesPerMinion / minions;

    // Total amount of time is fixed time plus ddr time
    result = 4000 + (size_t)ddrCycles;
  }

  return result;
}

size_t getImplementation(const std::string& operatorName, const std::vector<Tensor>& outOperands,
                         const std::vector<Tensor>& inOperands) {
  instrConfigInt instConfig;
  // If the operator doesn't exist, return a negative
  if (!getInstrConfig(operatorName, instConfig)) {
    return (size_t)-1;
  }

  // Converts the Tensor to LibTensor
  std::vector<std::unique_ptr<LibTensor>> outOperandsConverted, inOperandsConverted;
  std::vector<LibTensor*> outOperandsConvertedPtr, inOperandsConvertedPtr;

  for (auto& operand : outOperands) {
    auto libTensor = std::make_unique<dnn_lib::LibTensor>(operand);
    outOperandsConvertedPtr.push_back(libTensor.get());
    outOperandsConverted.push_back(std::move(libTensor));
  }
  for (auto& operand : inOperands) {
    auto libTensor = std::make_unique<dnn_lib::LibTensor>(operand);
    inOperandsConvertedPtr.push_back(libTensor.get());
    inOperandsConverted.push_back(std::move(libTensor));
  }
  return instConfig.implSel(outOperandsConvertedPtr, inOperandsConvertedPtr);
}

} // end namespace dnn_lib
