#ifndef COMMON_ARGUMENTS_H
#define COMMON_ARGUMENTS_H

#define L2_CACHE_BANKS (4)
#define L1_FLUSH_RESERVATION_START_LINE (16384)
#define L1_FLUSH_RESERVATION_LINES (8)
#ifndef CACHE_LINE_BYTES
#define CACHE_LINE_BYTES (64)
#endif

#endif

