import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/dnn-library-api.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "dnnLibraryApi"
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/ml-compiler"

stages:
  CHECKOUT_SCM:
    when:
      jenkins: true
      default: false
    cmds:
      # This script retries up to 8 times the checkout process, with an increasing sleep between retries
      - raw_cmd: |-
          script {
            def seconds = -1
            retry(8) {
              seconds = seconds * 2 + 2
              sleep(time: seconds, unit: "SECONDS")
              scm_variables = checkout([
                $class: 'GitSCM',
                branches: [[name: BRANCH]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[
                  credentialsId: 'aws_private_key',
                  url: "${REPO_SSH_URL}"
                ]]
              ])
              env.GIT_COMMIT = scm_variables.get('GIT_COMMIT')
            }
          }
      # This should disable Jenkins job, and use Gitlab-ci instead
      - raw_cmd: |-
          script {
            sh 'echo "Only gitlab-ci files changed. Skipping the pipeline..."'
            currentBuild.getRawBuild().getExecutor().interrupt(Result.UNSTABLE)
            sleep(1)   // Interrupt is not blocking and does not take effect immediately.
          }
      - raw_cmd: |-
          updateGitlabCommitStatus name: JOB_NAME, state: 'pending'
    exec_before: [r".*"]

  CLANG_CHECK:
    cmds:
      - job: sw-platform/host-sw-integration/pipelines/dnn-lib-api/dnn-lib-api-clang-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibraryApi:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_before: [r"JOB_.*"]
    exec_after: ['DSL_JOB']

  CODE_QUALITY:
    cmds:
      - job: sw-platform/code-analysis/dnnLibraryApi-sonarqube
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          GITLAB_SOURCE_BRANCH:
            raw_cmd: '"${env.gitlabSourceBranch}"'
          GITLAB_TARGET_BRANCH: 
            raw_cmd: '"${env.gitlabTargetBranch}"'
          GITLAB_MR_ID: 
            raw_cmd: '"${env.gitlabMergeRequestIid}"'
          COMPONENT_COMMITS: "host-software/dnnLibraryApi:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_after: ['CLANG_CHECK']

  DNN_LIB_CI:
    cmds:
      - job: sw-platform/host-sw-integration/pipelines/dnn-lib-checkin-top-level
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibraryApi:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_after: ['CLANG_CHECK']

  GLOW_FRONTEND_CI:
    cmds:
      - job: sw-platform/glow-integration/pipelines/glow-test-plan/frontend-etrt-devfw-sysemu
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibraryApi:${BRANCH}, ${COMPONENT_COMMITS}"
          REPO_SSH_URL: "git@gitlab.esperanto.ai:software/sw-platform.git"
          REPO_NAME: "sw-platform"
          TIMEOUT: "12"
    exec_after: ['CLANG_CHECK']
