include:
  - project: 'software/gitlab-ci-common'
    ref: 65f50069493bf125f770dc052b0a90b8be2d305c
    file:
      - rules/generic-workflow-conan.yaml
      - pods/large-pod.yaml
      - jobs/generic-k8s-job.yaml
      - rules/exec_maybe_interactively.yaml
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - test
  
default:
  interruptible: true


variables:
  ET_SW_DEVELOP_DOCKER_IMAGE:
    value: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-18.04-et-sw-develop-stack:0.3.2


.tests:common:
  extends:
    - .pod_large
    - .template_job
  variables:
    KUBERNETES_MEMORY_LIMIT: 16Gi
    ET_SDK_HOME: /usr/local/esperanto
    # DEVICE_TYPE: type of execution (silicon or sysemu)
    # LAUNCHERS_BASE_PATH: path to compiled host kernel launchers (examples)
    # KERNELS_BASE_PATH: path to compiled device kernels

    CMD_SETUP_EXTRA_DEPS: |
      sudo apt install ninja-build
    CMD_POST_BUILD: |
      source ${ET_SDK_HOME}/.builds/device/conanbuild.sh
      source ${ET_SDK_HOME}/.builds/host/conanrun.sh

      if [ "$BUILD_TYPE" == "Debug" ]; then
        echo "Skip testing when building in Debug"
      else

        cd host/build
        ./${LAUNCHERS_BASE_PATH}/basic_launcher -kernel_path=${KERNELS_BASE_PATH}/print.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print"
        fi      
        dt2json traceKernels_dev0_0.bin -t

        ./${LAUNCHERS_BASE_PATH}/basic_launcher -kernel_path=${KERNELS_BASE_PATH}/print2.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print2"
        fi            
        dt2json traceKernels_dev0_0.bin -t

        ./${LAUNCHERS_BASE_PATH}/basic_launcher -kernel_path=${KERNELS_BASE_PATH}/bss.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at bss"
        fi            
        dt2json traceKernels_dev0_0.bin -t

        ./${LAUNCHERS_BASE_PATH}/basic_launcher -kernel_path=${KERNELS_BASE_PATH}/data.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at data"
        fi                  
        dt2json traceKernels_dev0_0.bin -t

        ./${LAUNCHERS_BASE_PATH}/fft_launcher -kernel_path=${KERNELS_BASE_PATH}/fftKernel.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at fftKernel"
        fi            
        dt2json traceKernels_dev0_0.bin -t

        #
        # Add more testes here
        #

      fi

###############################################################################
###############################################################################
###############################################################################

.tests:conan:common:
  extends:
    - .pod_large
    - .template_job
    - .tests:common
  stage: test
  parallel:
    matrix:
      - BUILD_TYPE: [ Release, Debug ]
  variables:
    TIMEOUT: 2h
    LAUNCHERS_BASE_PATH: ${BUILD_TYPE}/sdk
    KERNELS_BASE_PATH: ../../device/build/Release/tests

    CMD_BUILD: |
      BUILD_TYPE_LOWER=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
      
      cd device
      cp ${ET_SDK_HOME}/.conanfiles/conanfile_device.txt conanfile.txt
      echo "[layout]" >> conanfile.txt
      echo "cmake_layout" >> conanfile.txt
      
      conan install . -pr:b default -pr:h baremetal-rv64-gcc8.2-release --remote conan-develop --build missing
      source build/generators/conanbuild.sh
      cmake --preset release -DADDRESS:STRING=0x8005b35000 -DUSE_CONAN=ON
      cmake --build --preset release
      cd ..

      cd host
      cp ${ET_SDK_HOME}/.conanfiles/conanfile_host.txt conanfile.txt
      echo "[layout]" >> conanfile.txt
      echo "cmake_layout" >> conanfile.txt
      
      conan install . -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-${BUILD_TYPE_LOWER} --update --remote conan-develop --build missing
      cmake --preset ${BUILD_TYPE_LOWER} -DUSE_CONAN=ON -G Ninja
      cmake --build --preset ${BUILD_TYPE_LOWER}
      cd ..

tests:conan:sw-sysemu:
  extends:
    - .tests:conan:common
  image: ${ET_SW_DEVELOP_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu


.tests:cmake-only:common:
  extends:
    - .pod_large
    - .template_job
    - .tests:common
  stage: test
  parallel:
    matrix:
      - BUILD_TYPE: [ Release, RelWithDebInfo, Debug ]
  variables:
    TIMEOUT: 2h
    LAUNCHERS_BASE_PATH: sdk
    KERNELS_BASE_PATH: ../../device/build/tests

    CMD_BUILD: |      
      cd device
      mkdir build && cd build
      source ${ET_SDK_HOME}/.builds/device/conanbuild.sh
      cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/local/esperanto/.builds/device/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DADDRESS:STRING=0x8005b35000 -DUSE_CONAN=ON
      cmake --build .
      cd ../..

      cd host
      mkdir build && cd build
      cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/local/esperanto/.builds/host/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_CONAN=ON -G Ninja
      cmake --build .
      cd ../..

tests:cmake-only:silicon:
  extends:
    - .tests:cmake-only:common
  image:
    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
    entrypoint: [""]
  variables:
    DEVICE_TYPE: silicon
  parallel:
    matrix:
      - BUILD_TYPE: [ Release ]
  tags:
    - silicon
    - 1-card-silicon
    - mv-gb-swci01
  
tests:cmake-only:sw-sysemu:
  extends:
    - .tests:cmake-only:common
  image: ${ET_SW_DEVELOP_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu
