include:
  - project: 'software/gitlab-ci-common'
    ref: 65f50069493bf125f770dc052b0a90b8be2d305c
    file:
      - rules/generic-workflow-conan.yaml
      - pods/large-pod.yaml
      - jobs/generic-k8s-job.yaml
      - rules/exec_maybe_interactively.yaml
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

stages:
  - test
  
default:
  interruptible: true


variables:
  ET_SW_DEVELOP_DOCKER_IMAGE:
    value: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-18.04-et-sw-develop-stack:0.1.26
  ET_CONAN_DOCKER_IMAGE:
    value: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/ubuntu-18.04-gcc7-conan:0.5.10


###############################################################################
###############################################################################
###############################################################################

.tests:conan:common:
  extends:
    - .pod_large
    - .template_job
  stage: test
  parallel:
    matrix:
      - BUILD_TYPE: [ Release, Debug ] #RelWithDebInfo doesn't exist
  variables:
    KUBERNETES_MEMORY_LIMIT: 16Gi
    TIMEOUT: 2h
    CMD_SETUP_EXTRA_DEPS: |
      sudo apt install ninja-build
    CMD_BUILD: |
      BUILD_TYPE_LOWER=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
      cd device
      conan install . -pr:b default -pr:h baremetal-rv64-gcc8.2-release --remote conan-develop --build missing
      source build/generators/conanbuild.sh
      cmake --preset release -DADDRESS:STRING=0x8005b35000 -DCMAKE_C_COMPILER=riscv64-unknown-elf-gcc -DCMAKE_CXX_COMPILER=riscv64-unknown-elf-g++ -DCMAKE_ASM_COMPILER=riscv64-unknown-elf-gcc -DUSE_CONAN=ON
      cmake --build --preset release
      cd ..

      cd host
      conan install .  -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-${BUILD_TYPE_LOWER} --update --remote conan-develop --build missing -o fftw:precision=single
      cmake --preset ${BUILD_TYPE_LOWER} -G Ninja
      cmake --build --preset ${BUILD_TYPE_LOWER}
      cd ..

    CMD_POST_BUILD: |
      if [ "$BUILD_TYPE" == "Debug" ]; then
        echo "Skip testing when building in Debug"
      else

        # install dt2json
        conan install trace-utils/0.6.0@ -pr:b default -pr:h linux-ubuntu18.04-x86_64-gcc7-release --remote conan-develop --build missing -o trace-utils:with_cereal=False -g VirtualRunEnv
        source conanrun.sh

        cd host/build
        ./${BUILD_TYPE}/sdk/basic_launcher -kernel_path=../../device/build/Release/tests/print.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print"
        fi      
        dt2json traceKernels_dev0_0.bin -t

        ./${BUILD_TYPE}/sdk/basic_launcher -kernel_path=../../device/build/Release/tests/print2.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print2"
        fi            
        dt2json traceKernels_dev0_0.bin -t

        ./${BUILD_TYPE}/sdk/basic_launcher -kernel_path=../../device/build/Release/tests/bss.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at bss"
        fi            
        dt2json traceKernels_dev0_0.bin -t

        ./${BUILD_TYPE}/sdk/basic_launcher -kernel_path=../../device/build/Release/tests/data.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at data"
        fi                  
        dt2json traceKernels_dev0_0.bin -t

        ./${BUILD_TYPE}/sdk/fft_launcher -kernel_path=../../device/build/Release/tests/fftKernel.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at fftKernel"
        fi            
        dt2json traceKernels_dev0_0.bin -t
        
        #
        # Add more testes here
        #

      fi

tests:conan:sw-sysemu:
  extends:
    - .tests:conan:common
  image: ${ET_CONAN_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu
#
# temporarily disabling silicon jobs
#
#tests:conan:silicon:
#  extends:
#    - .tests:conan:common
#  image:
#    name: ${ET_CONAN_DOCKER_IMAGE}
#    entrypoint: [""]
#  tags:
#    - silicon
#    - mv-eap03
#  variables:
#    DEVICE_TYPE: silicon
#  allow_failure: true

.tests:cmake-only:common:
  extends:
    - .pod_large
    - .template_job
  stage: test
  parallel:
    matrix:
      - BUILD_TYPE: [ Release, RelWithDebInfo, Debug ]
  variables:
    KUBERNETES_MEMORY_LIMIT: 16Gi
    TIMEOUT: 2h
    CMD_SETUP_EXTRA_DEPS: |
      sudo apt install ninja-build
    CMD_BUILD: |
      cd device
      mkdir build && cd build
      cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/local/esperanto/.builds/device/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DADDRESS:STRING=0x8005b35000 -DCMAKE_C_COMPILER=riscv64-unknown-elf-gcc -DCMAKE_CXX_COMPILER=riscv64-unknown-elf-g++ -DCMAKE_ASM_COMPILER=riscv64-unknown-elf-gcc -DUSE_CONAN=ON
      cmake --build .
      cd ../..

      cd host
      mkdir build && cd build
      cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/local/esperanto/.builds/host/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_CONAN=ON -G Ninja
      cmake --build .
      cd ../..

    CMD_POST_BUILD: |
      export ET_SDK_HOME=/usr/local/esperanto
      source ${ET_SDK_HOME}/.builds/device/conanbuild.sh
      source ${ET_SDK_HOME}/.builds/host/conanrun.sh
      
      if [ "$BUILD_TYPE" == "Debug" ]; then
        echo "Skip testing when building in Debug"
      else

        cd host/build
        ./sdk/basic_launcher -kernel_path=../../device/build/tests/print.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print"
        fi
        dt2json traceKernels_dev0_0.bin -t

        ./sdk/basic_launcher -kernel_path=../../device/build/tests/print2.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at print2"
        fi     
        dt2json traceKernels_dev0_0.bin -t

        ./sdk/basic_launcher -kernel_path=../../device/build/tests/bss.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at bss"
        fi      
        dt2json traceKernels_dev0_0.bin -t

        ./sdk/basic_launcher -kernel_path=../../device/build/tests/data.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at data"
        fi      
        dt2json traceKernels_dev0_0.bin -t

        ./sdk/fft_launcher -kernel_path=../../device/build/tests/fftKernel.elf -device-type=${DEVICE_TYPE}
        if [ $? -ne 0 ]; then
          echo "Error at fftkernel"
        fi
        dt2json traceKernels_dev0_0.bin -t
      
        #
        # Add more testes here
        #

      fi

tests:cmake-only:sw-sysemu:
  extends:
    - .tests:cmake-only:common
  image: ${ET_SW_DEVELOP_DOCKER_IMAGE}
  variables:
    DEVICE_TYPE: sysemu

# 
# Temporarily disabled silicon testing on the CI as it seems unreasonably slow & creates contention.
#
#tests:cmake-only:silicon:
#  extends:
#    - .tests:cmake-only:common
#  image:
#    name: ${ET_SW_DEVELOP_DOCKER_IMAGE}
#    entrypoint: [""]
#  tags:
#    - silicon
#    - mv-eap03
#  variables:
#    DEVICE_TYPE: silicon
#  allow_failure: true
