sonar.projectKey=software_gp-sdk_AYYTV7LEqWmeIuDQiLCF
sonar.qualitygate.wait=true
sonar.cfamily.compile-commands=compile_commands.json
sonar.python.version=3.9, 3.10, 3.11, 3.12, 3.13
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=.sonar/cache