import:
  - path: '@ci@/ci-tools/templates/template-main-top-level.yaml'

parameters:
  REPO_SSH_URL:
    description: Repository URL
    type: string
    default_value: "git@gitlab.esperanto.ai:software/dnn-library.git"
  REPO_NAME:
    description: Repository name
    type: string
    default_value: "dnn-library"
  SW_PLATFORM_BRANCH:
    description: SW-Platform branch to track
    type: string
    default_value: "origin/develop/ml-compiler"

stages:
  CLANG_CHECK:
    cmds:
      - job: sw-platform/host-sw-integration/pipelines/dnn-lib/dnn-lib-clang-tests
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibrary:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_before: [r"JOB_.*"]
    exec_after: ['DSL_JOB']

  AUTO_CODE_GEN:
    cmds:
      - job: sw-platform/host-sw-integration/pipelines/dnn-lib/dnn-lib-automatic-code-gen-ci
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibrary:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_after: ['CLANG_CHECK']

  GLOW_CI:
    cmds:
      - job: sw-platform/glow-integration/glow-checkin-top-level
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibrary:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_after: ['CLANG_CHECK']

  DNN_LIB_CI:
    cmds:
      - job: sw-platform/host-sw-integration/pipelines/dnn-lib-checkin-top-level
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibrary:${BRANCH}, ${COMPONENT_COMMITS}"
    exec_after: ['CLANG_CHECK']

  GLOW_FRONTEND_CI:
    cmds:
      - job: sw-platform/glow-integration/pipelines/glow-test-plan/frontend-etrt-devfw-sysemu
        parameters:
          BRANCH: "${SW_PLATFORM_BRANCH}"
          COMPONENT_COMMITS: "host-software/dnnLibrary:${BRANCH}, ${COMPONENT_COMMITS}"
          REPO_SSH_URL: "git@gitlab.esperanto.ai:software/sw-platform.git"
          REPO_NAME: "sw-platform"
          TIMEOUT: "12"
    exec_after: ['CLANG_CHECK']
