include:
  - project: software/gitlab-ci-common
    ref: 63d36bead3e7d23e58cffc81487d7e317895cc76
    file:
      - /rules/generic-workflow.yaml
      - /jobs/generic-k8s-job.yaml
      - /pods/medium-pod.yaml
      - /rules/exec_maybe_interactively.yaml
      - /jobs/check-top-of-master.yaml
      - /jobs/sw-platform-trigger.yaml

default:
  interruptible: true

stages:
  - generate_build
  - build
  - test

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/ml-compiler
  PIPELINE_CI_SUBPROJECT: dnnLibraryApi

clang-format:
  extends:
    - .template_job
    - .pod_medium
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.0
  stage: .pre
  variables:
    CMD_SCRIPT: |
      git fetch origin master
      git clang-format --diff origin/master -- * | grep -e "clang-format did not modify any files$" -e "^no modified files to format$"
      
# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml
