include:
  - project: software/gitlab-ci-common
    ref: 63d36bead3e7d23e58cffc81487d7e317895cc76
    file:
      - /rules/generic-workflow.yaml
      - /jobs/generic-k8s-job.yaml
      - /pods/medium-pod.yaml
      - /rules/exec_maybe_interactively.yaml
      - /jobs/check-top-of-master.yaml
      - /jobs/sw-platform-trigger.yaml
  - project: 'software/gitlab-ci-common'
    ref: master
    file:
      - 'jobs/conan-jobs.yaml'

default:
  interruptible: true

stages:
  - generate_build
  - build
  - test
  - deploy

variables:
  # These two variables are consumed by the jobs from /jobs/sw-platform-trigger.yaml
  SW_PLATFORM_BRANCH: develop/ml-compiler
  PIPELINE_CI_SUBPROJECT: dnnLibraryApi

clang-format:
  extends:
    - .template_job
    - .pod_medium
  image: docker-sw-team.sc-artifactory1.esperanto.ai/convoke/centos-7.9.2009-et-sw-platform:0.3.0
  stage: .pre
  variables:
    CMD_SCRIPT: |
      git fetch origin master
      git clang-format --diff origin/master -- * | grep -e "clang-format did not modify any files$" -e "^no modified files to format$"

###############################################################################
###############################################################################
###############################################################################

# Generates conan child pipeline
generate_build:conan:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: generate_build
  variables:
    TIMEOUT: 15m
    CMD_BUILD: |
      cd conan
      python3 -m ci_build
  artifacts:
    expire_in: 6h 
    paths:
      - conan/build_pipeline.yml
      - conan/lockfiles_info.json

###############################################################################
###############################################################################
###############################################################################

# conan child build pipeline
build:conan:
  stage: build
  needs:
    - generate_build:conan
  stage: build
  trigger:
    include:
    - artifact: conan/build_pipeline.yml
      job: generate_build:conan
    strategy: depend

###############################################################################
###############################################################################
###############################################################################

# integration testing with sw-platform
#
# This is automatically done thanks to this included file:
#   /jobs/sw-platform-trigger.yaml

###############################################################################
###############################################################################
###############################################################################

on_success:promote:
  extends:
    - .pod_nano
    - .template_job
    - .template-conan-linux-ubuntu18.04-gcc7
  stage: deploy
  needs:
    - generate_build:conan
    - build:conan
    - meta-trigger
  variables:
    PYTHONIOENCODING: utf-8
    CMD_BUILD: |
      cd conan
      python3 -m ci_promote

###############################################################################
###############################################################################
###############################################################################
