sonar.projectKey=dnnLibraryApi
sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
sonar.cfamily.cache.enabled=false
sonar.sources=src,include
sonar.exclusions=ci,build
sonar.sourceEncoding=utf-8
sonar.cfamily.threads=8
